api:
  prefix: /api
cellphone: {}
database:
  adapter: postgresql+psycopg2
  db_name:
  host: localhost
  password:
  port: 5432
  user:
flask:
  debug: false
  sqlalchemy_track_modifications: false
  secret_key: 5e7ca92615435457f491e6546ee4b092a6497a47d894bb21
